project_id = "eecxwrxxtbaecbblpovl"

[functions.notify-application-status]
verify_jwt = false

[functions.request-password-reset]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.send-signup-verification]
verify_jwt = false

[functions.netlify-mcp]
verify_jwt = false